import type {
  ActivityItem,
  Card,
  DocItem,
  Person,
} from "@/lib/types"

export const BUILDING_NAME = "Harbourview Residences"

export const initialCards: Card[] = [
  {
    id: "u-1001",
    type: "update",
    title: "Lift 2 maintenance scheduled this Thursday",
    area: "Lift",
    status: "Published",
    publishDate: "2026-07-28",
    summary:
      "Lift 2 will be out of service from 9am to 1pm for its annual safety inspection.",
    body: "Our maintenance contractor will carry out the annual safety inspection on Lift 2 this Thursday between 9am and 1pm. During this window, please use Lift 1 or the north stairwell. We apologise for any inconvenience and appreciate your patience while we keep the building safe and compliant.",
    audience: "All residents",
    commentCount: 6,
    attachments: ["lift-inspection-notice.pdf"],
    createdAt: "2026-07-26T09:00:00Z",
    comments: [
      {
        id: "c1",
        author: "Dana Whitfield",
        initials: "DW",
        body: "Thanks for the heads up. Will the parcel lift be affected too?",
        date: "2026-07-27",
      },
      {
        id: "c2",
        author: "Building Manager",
        initials: "BM",
        body: "No, the parcel lift stays fully operational during this window.",
        date: "2026-07-27",
      },
    ],
  },
  {
    id: "u-1002",
    type: "update",
    title: "New recycling stations in the parking level",
    area: "Parking",
    status: "Published",
    publishDate: "2026-07-22",
    summary:
      "Three new sorting stations for glass, paper and soft plastics are now available on P1.",
    body: "To help us hit our building sustainability targets, three new recycling sorting stations have been installed on parking level P1 near the loading bay. Please rinse containers before disposal and break down cardboard boxes. Signage explains what goes where.",
    audience: "All residents",
    commentCount: 3,
    attachments: [],
    createdAt: "2026-07-20T09:00:00Z",
    comments: [],
  },
  {
    id: "u-1003",
    type: "update",
    title: "Lobby refurbishment — final design approved",
    area: "Lobby",
    status: "Scheduled",
    publishDate: "2026-08-05",
    summary:
      "The committee approved the final lobby design. Works begin mid-August.",
    body: "Following resident feedback, the committee has approved the final lobby refurbishment design. Works are expected to begin mid-August and run for approximately six weeks. A temporary reception desk will be set up near the mailroom.",
    audience: "Owners",
    commentCount: 0,
    attachments: ["lobby-design-final.pdf"],
    createdAt: "2026-07-25T09:00:00Z",
    comments: [],
  },
  {
    id: "u-1004",
    type: "update",
    title: "Quarterly strata levy notice",
    area: "Strata",
    status: "Draft",
    publishDate: "",
    summary:
      "Draft notice for the Q3 strata levies. Pending committee review before publishing.",
    body: "This is a draft of the Q3 strata levy notice. Amounts are pending final confirmation from the treasurer. Do not publish until the committee has signed off on the figures at the next meeting.",
    audience: "Owners",
    commentCount: 0,
    attachments: [],
    createdAt: "2026-07-29T09:00:00Z",
    comments: [],
  },
  {
    id: "u-1005",
    type: "update",
    title: "Pool reopening after resurfacing",
    area: "Pool",
    status: "Archived",
    publishDate: "2026-06-10",
    summary:
      "The rooftop pool reopened following resurfacing works. Thank you for your patience.",
    body: "The rooftop pool has reopened following the resurfacing works completed last month. New non-slip tiling has been installed around the perimeter. Normal pool hours of 6am to 10pm now apply.",
    audience: "All residents",
    commentCount: 9,
    attachments: [],
    createdAt: "2026-06-08T09:00:00Z",
    comments: [],
  },
  {
    id: "v-2001",
    type: "vote",
    title: "Approve the 2026 garden landscaping budget of $18,000?",
    area: "Garden",
    status: "Closing soon",
    deadline: "2026-08-03",
    description:
      "The committee proposes a $18,000 budget to redesign the courtyard garden with drought-tolerant planting, new seating and improved lighting.",
    participation: 42,
    eligibleCount: 60,
    options: [
      { id: "o1", label: "Approve the budget", votes: 31 },
      { id: "o2", label: "Reject the budget", votes: 8 },
      { id: "o3", label: "Defer to next meeting", votes: 3 },
    ],
    resultsHidden: false,
    userVoted: false,
    audience: "Owners",
    eligibility: "One vote per lot owner",
    createdAt: "2026-07-20T09:00:00Z",
  },
  {
    id: "v-2002",
    type: "vote",
    title: "Should we install EV charging stations on P2?",
    area: "Parking",
    status: "Open",
    deadline: "2026-08-14",
    description:
      "Proposal to install four shared EV charging stations on parking level P2, funded from the capital works fund.",
    participation: 18,
    eligibleCount: 60,
    options: [
      { id: "o1", label: "Yes, install four stations", votes: 12 },
      { id: "o2", label: "Yes, but start with two", votes: 4 },
      { id: "o3", label: "No, not at this time", votes: 2 },
    ],
    resultsHidden: true,
    userVoted: false,
    audience: "Owners",
    eligibility: "One vote per lot owner",
    createdAt: "2026-07-24T09:00:00Z",
  },
  {
    id: "v-2003",
    type: "vote",
    title: "Preferred quiet hours for the shared gym",
    area: "Gym",
    status: "Open",
    deadline: "2026-08-20",
    description:
      "Help us set quiet hours for the shared gym when loud music and dropping weights are discouraged.",
    participation: 27,
    eligibleCount: 88,
    options: [
      { id: "o1", label: "10pm – 6am", votes: 19 },
      { id: "o2", label: "9pm – 7am", votes: 6 },
      { id: "o3", label: "No quiet hours", votes: 2 },
    ],
    resultsHidden: false,
    userVoted: true,
    audience: "All residents",
    eligibility: "One vote per resident",
    createdAt: "2026-07-22T09:00:00Z",
  },
  {
    id: "v-2004",
    type: "vote",
    title: "Committee proposal: update the pet policy",
    area: "Building-wide",
    status: "Closed",
    deadline: "2026-07-15",
    description:
      "A proposal to allow up to two pets per lot with committee approval, replacing the current one-pet limit.",
    participation: 54,
    eligibleCount: 60,
    options: [
      { id: "o1", label: "Approve the new policy", votes: 38 },
      { id: "o2", label: "Keep the current policy", votes: 16 },
    ],
    resultsHidden: false,
    userVoted: true,
    audience: "Owners",
    eligibility: "One vote per lot owner",
    createdAt: "2026-06-25T09:00:00Z",
  },
  {
    id: "v-2005",
    type: "vote",
    title: "Draft: rooftop BBQ booking system",
    area: "Rooftop",
    status: "Draft",
    deadline: "",
    description:
      "Draft proposal to introduce an online booking system for the rooftop BBQ area on weekends.",
    participation: 0,
    eligibleCount: 88,
    options: [
      { id: "o1", label: "Introduce a booking system", votes: 0 },
      { id: "o2", label: "Keep it first-come, first-served", votes: 0 },
    ],
    resultsHidden: true,
    userVoted: false,
    audience: "All residents",
    eligibility: "One vote per resident",
    createdAt: "2026-07-29T09:00:00Z",
  },
]

export const people: Person[] = [
  { id: "p1", name: "Dana Whitfield", initials: "DW", contextLabel: "Unit 12A", role: "Committee", email: "dana.w@harbourview.com" },
  { id: "p2", name: "Marcus Lee", initials: "ML", contextLabel: "Unit 07B", role: "Owner", email: "marcus.lee@mail.com" },
  { id: "p3", name: "Priya Nadar", initials: "PN", contextLabel: "Unit 21C", role: "Resident", email: "priya.n@mail.com" },
  { id: "p4", name: "Tom Okafor", initials: "TO", contextLabel: "Unit 03A", role: "Tenant", email: "tom.okafor@mail.com" },
  { id: "p5", name: "Sofia Alvarez", initials: "SA", contextLabel: "Unit 18D", role: "Owner", email: "sofia.a@mail.com" },
  { id: "p6", name: "Henry Bao", initials: "HB", contextLabel: "Unit 09A", role: "Committee", email: "henry.bao@mail.com" },
  { id: "p7", name: "Grace Miller", initials: "GM", contextLabel: "Unit 15B", role: "Manager", email: "grace@harbourview.com" },
  { id: "p8", name: "Ravi Shankar", initials: "RS", contextLabel: "Unit 22A", role: "Owner", email: "ravi.s@mail.com" },
]

export const documents: DocItem[] = [
  { id: "d1", name: "Fire safety evacuation plan 2026", category: "Fire safety", fileSize: "2.4 MB", extractionStatus: "Demo record", updated: "2026-07-01" },
  { id: "d2", name: "Annual fire equipment inspection report", category: "Fire safety", fileSize: "1.1 MB", extractionStatus: "Demo record", updated: "2026-06-18" },
  { id: "d3", name: "Strata by-laws (consolidated)", category: "Governance", fileSize: "820 KB", extractionStatus: "Demo record", updated: "2026-05-30" },
  { id: "d4", name: "Building insurance certificate of currency", category: "Insurance", fileSize: "460 KB", extractionStatus: "Demo record", updated: "2026-04-12" },
  { id: "d5", name: "Q2 committee meeting minutes", category: "Minutes", fileSize: "310 KB", extractionStatus: "Demo record", updated: "2026-07-05" },
  { id: "d6", name: "Lobby refurbishment — final design", category: "Projects", fileSize: "5.7 MB", extractionStatus: "Demo record", updated: "2026-07-25" },
]

export const activity: ActivityItem[] = [
  { id: "a1", sourceRef: "fallback-activity:a1", actor: "Building Manager", initials: "BM", action: "published", target: "Lift 2 maintenance scheduled", time: "2h ago" },
  { id: "a2", sourceRef: "fallback-activity:a2", actor: "Dana Whitfield", initials: "DW", action: "commented on", target: "Lift 2 maintenance", time: "4h ago" },
  { id: "a3", sourceRef: "fallback-activity:a3", actor: "Sofia Alvarez", initials: "SA", action: "voted on", target: "Garden landscaping budget", time: "6h ago" },
  { id: "a4", sourceRef: "fallback-activity:a4", actor: "Grace Miller", initials: "GM", action: "scheduled", target: "Lobby refurbishment update", time: "1d ago" },
  { id: "a5", sourceRef: "fallback-activity:a5", actor: "Marcus Lee", initials: "ML", action: "voted on", target: "Gym quiet hours", time: "1d ago" },
  { id: "a6", sourceRef: "fallback-activity:a6", actor: "Committee", initials: "CO", action: "closed", target: "Pet policy update", time: "3d ago" },
]

export const BUILDING_AREAS: string[] = [
  "Lobby",
  "Lift",
  "Strata",
  "Parking",
  "Garden",
  "Rooftop",
  "Pool",
  "Gym",
  "Building-wide",
]

export const AUDIENCES: string[] = [
  "All residents",
  "Owners",
  "Committee",
  "Tenants",
]
